config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
    resource :tags, only: [:create, :destroy]
    get :search, on: :collection
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "relationships/followings" => "relationships#followings", as: "followings"
    get "relationships/followers" => "relationships#followers", as: "followers"
  end
  get "search" => "searches#search"
  get "home/about" => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :profile_image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :user_id, presence: true
  validates :star, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  scope :search_by_name, ->(search){where(['name LIKE?', "#%{search}%"])}
  scope :latest, -> {order(create_at: :desc)}
  scope :star_count, -> {order(star: :desc)}
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      Book.where(title: word)
    elsif search == "forward_match"
     Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
     Book.where("title LIKE?", "%#{word}")
    elsif search == "pertial_match"
      Book.where("title LIKE?", "%#{word}%")
    else
     Book.all
    end
  end

  def save_tags(sevebok_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - sevebook_tags
    new_tags = sevebook_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name: old)
    end
    new_tags.each do |new_name|
      book_tag = Tag.find_or_create_by(name: new_name)
      self.tags << book_tag
    end
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE?', '%'+content)
    else
      Book.where('title LIKE?', '%'+content+'%')
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
   before_action :ensure_correct_user, only: [:edit, :update, :destroy]
   def new
     @book = Book.new
   end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    tag_list = params[:book][:name].split(',')
    if @book.save
      @book.save_tags(tag_list)
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    @book_tags = @book.tags

  end



  def index
    if params[:latest]
      @books = Book.latest
    elsif params[:star_count]
      @books = Book.star_count
    else
     @books = Book.all
    end
    @book = Book.new
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user = current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star)
  end

  def tag_paramas
    params.require(:book).permit(:name)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book, local:true  do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "form-control book_title" %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: "form-control book_body" %>
  </div>
  <div class="form-group">
    <label for="tag_name">Tag</label>
    <%= f.text_field :name, class: "form-control tag_name" %>
  </div>
  <div class="row" id="star">
    <%= f.label :star,'評価 ', class:"form-control label" %>
    <%= f.hidden_field :star, id: :review_star %>
  </div>
  <script>
  　$('#star').empty();
    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      half: true,
      scoreName: 'book[star]',
    });
  </script>
  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th>Tag</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% books.each do |book| %>
        <tr>
          <td><%= link_to book.user do %>
            <%= image_tag book.user.get_profile_image(40, 40) %>
            <% end %>
          </td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
          <td>
            <% book.tags.each do |tag| %>
             <li style="list-style: none;"><%= link_to tag.name, search_path(content: tag.name, model:"tag", method: "perfect") %></li>
            <% end %>
          </td>
          <td class="favorite-btn_<%= book.id %>">
           <%= render 'favorites/favorite-btn', book: book %>
          </td>
          <td>コメント数: <%= book.book_comments.count %></td>
          <td id="star-rate-<%= book.id %>"></td>
          <script>
          　$('#star-rate-<%= book.id %>').empty();
            $('#star-rate-<%= book.id %>').raty({
              size: 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= book.star %>,
            });
          </script>
        </tr>
      <% end %>
    </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @book %>
  		<%= form_with model: @book do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class: 'form-control book_body' %>
      </div>
      <div class="row" id="star">
    <%= f.label :star,'評価 ', class:"form-control label" %>
    <%= f.hidden_field :star, id: :review_star %>
  </div>
  <script>
  　$('#star').empty();
    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      half: true,
      readOnly: true,
      scoreName: 'book[star]',
    });
  </script>
      <div class="form-group">
        <%= f.submit 'Update Book', class: 'btn btn-success' %>
      </div>
      <% end %>
      		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
      		<%= link_to 'Back', books_path, class: "back" %>
      </div>
</div>

app/views/books/index.html.erb
 <div class="container px-5 px-sm-0">
    <%= render 'layouts/errors', obj: @book %>
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= render 'users/info', user: current_user %>
        <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <div>
          <%= link_to "新着順", books_path(latest: "true") %>
          |<%= link_to "評価が高い順", books_path(star_count: "true") %>
        </div>
        <%= render 'books/index', books: @books %>
      </div>
    </div>
 </div>

app/views/books/show.html.erb
 <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= render 'users/info', user: @user %>
        <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book_new %>
      </div>
      <div class="col-md-8 offset-md-1">
    		<h2>Book detail</h2>
    	  <table class="table">
           <tr>
            <td><%= link_to @book.user do %>
              <%= image_tag @book.user.get_profile_image(40, 40) %><br>
              <%= @book.user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <% @book.tags.each do |tag| %>
             <td><%= tag.name %></td>
            <% end %>
            <td class="favorite-btn_<%= @book.id %>">
             <%= render 'favorites/favorite-btn', book: @book %>
            </td>
            <td>コメント数: <%= @book.book_comments.count %></td>
            <td id="star-rate-<%= @book.id %>"></td>
            <script>
            　$('#star-rate-<%= @book.id %>').empty();
              $('#star-rate-<%= @book.id %>').raty({
                size: 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= @book.star %>,
              });
            </script>
            <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success edit_book" %></td>
              <td><%= link_to "Destroy", book_path(@book.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book" %></td>
            <% end %>
        </tr>
        </table>
         <div class="comments-area"><%= render 'book_comments/comment', book: @book, book_comment: @book_comment %></div>
      </div>
    </div>
 </div>